{
 "title": "Sample Jaeger tracing dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "container", "label": "Container", "query": "label_values(container)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kube_pod_container_info{container=~\"$container\"}, pod)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{container=\"$container\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Span count distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(span_seconds_count{container=\"$container\"}[1m])) without (pod_name,instance,job,pod_template_hash,namespace,transaction,error)"
    }
   ]
  },
  {
   "title": "Average span duration over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(span_seconds_sum{container=\"$container\"}[1m])) without (pod_name,instance,job,namespace,pod_template_hash,transaction,error)"
    }
   ]
  },
  {
   "title": "Service error ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(span_seconds_count{error=\"true\",span_kind=\"server\",container=\"$container\"}[1m])) without (pod,instance,job,namespace,endpoint,transaction,error,operation,span_kind) / sum(increase(span_seconds_count{span_kind=\"server\",container=\"$container\"}[1m])) without (pod,instance,job,namespace,endpoint,transaction,error,operation,span_kind)"
    }
   ]
  }
 ]
}