---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: event
          image: ammbra/event:0.0.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - name: prometheus-jmx
              containerPort: 9099
          env:
          - name: JAEGER_SERVICE_NAME
            value: event
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"

---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  labels:
    app: event
spec:
  type: LoadBalancer
  selector:
    app: event
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-service-monitor
spec:
  selector:
    matchLabels:
      app: event
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"