---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itinerary
  labels:
    app: itinerary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itinerary
  template:
    metadata:
      labels:
        app: itinerary
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: itinerary
          image: ammbra/itinerary:0.0.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - name: prometheus-jmx
              containerPort: 9099
          env:
          - name: JAEGER_SERVICE_NAME
            value: itinerary
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
          - name: LANDMARK_URL
            value: "http://landmark-service:8080/landmark"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"

---
apiVersion: v1
kind: Service
metadata:
  name: itinerary-service
  labels:
    app: itinerary
spec:
  type: LoadBalancer
  selector:
    app: itinerary
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: itinerary-service-monitor
spec:
  selector:
    matchLabels:
      app: itinerary
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"