spring:
    application:
        name: itinerary
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
    metrics:
        tags:
            application: ${spring.application.name}
opentracing:
    spring:
        cloud:
            log:
                enabled: true
testFlagEnabled: ${TEST_FLAG_ENABLED:false}